exp_tags: "Digits: USPS to MNIST"
img_size: 64
device: "cuda"
mc_samples: 16
alignment_mode: "soft"

alpha_unc: 0.25
alpha_div: 0.15
alpha_adv: 0.02
alpha_ssl: 0.15

dataset:
  source: "usps"
  target: "mnist" 
  num_classes: 10

burn_in: 
  epochs: 20
  train_bs: 64
  eval_bs: 512
  num_workers: 8

domain_adapt:
  epochs: 50
  train_bs: 128
  eval_bs: 256
  num_workers: 8
  unc_thres_start: 1.5
  unc_thres_end: 0.1

domain_dis: 
  hidden_dim: 128
  num_res_blocks: 0
  dropout: 0.5

model:
  backbone: 
    type: "resnet18"
    in_dim: 512
    hidden_dim: 96
    num_res_blocks: 0
    freeze: True
  
  patch_size: 4
  attribute_layers: 5

  source:
    vr_dropout: 0.1
    cls_dropout: 0.3
    tau_s: 0.9
    tau_t: 0.9

  target: 
    vr_dropout: 0.1
    cls_dropout: 0.3
    tau: 0.9

optimizer:
  lr: 0.0003
  weight_decay: 0.0001

optimizer_d:
  lr: 0.0003
  weight_decay: 0.0001

optimizer_vr:
  lr: 0.0005
  weight_decay: 0.00001


