epochs: 1
img_size: 64
device: "cuda:0"
mc_samples: 4
tau: 0.9
t_u: 0.2


dataset:
  source: "mnist"
  target: "usps"
  train_bs: 256
  eval_bs: 256
  num_classes: 10

model:
  backbone: 
    type: "resnet18"
    in_dim: 512
    hidden_dim: 256
    freeze: True
  
  patch_size: 4
  attribute_layers: 5
  source: 
    vr_dropout: 0.5
    cls_dropout: 0.3
  target: 
    vr_dropout: 0.3
    cls_dropout: 0.7

optimizer:
  lr: 0.001
  weight_decay: 0.0005

optimizer_vr:
  lr: 0.0002
  weight_decay: 0.00001


