exp_tags: "Office31: Amazon to Webcam"
epochs: 20
img_size: 224
device: "cuda"
mc_samples: 8
tau: 1.2

dataset:
  source: "office31_amazon"
  target: "office31_webcam"
  train_bs: 32
  eval_bs: 256
  num_classes: 31
  num_workers: 4

model:
  backbone: 
    type: "resnet50"
    in_dim: 2048
    hidden_dim: 256
    num_res_blocks: 0
    freeze: True
  
  patch_size: 32
  attribute_layers: 6
  source:
    vr_dropout: 0.3
    cls_dropout: 0.5
  target: 
    vr_dropout: 0.7
    cls_dropout: 0.5

optimizer:
  lr: 0.0003
  weight_decay: 0.0001

optimizer_d:
  lr: 0.0002
  weight_decay: 0.0001

optimizer_vr:
  lr: 0.0005
  weight_decay: 0.0005


